"use client";

import { useEffect, useState } from "react";
import { disabledStyle, h2Style, inputStyle, secondaryButtonStyle, sectionStyle } from "./dashboard-ui";

type Blog = { id: string; name: string };
type Connection = { connected: boolean; blogId?: string; blogName?: string; blogs?: Blog[]; isExpired?: boolean };
type Settings = { configured: boolean; isAdmin?: boolean; clientId?: string | null; rawClientId?: string };

export default function BloggerSection({ allowed = true }: { allowed?: boolean }) {
  const [connection, setConnection] = useState<Connection | null>(null);
  const [selected, setSelected] = useState("");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [editing, setEditing] = useState(false);
  const [clientId, setClientId] = useState("");
  const [clientSecret, setClientSecret] = useState("");
  async function load() { try { const [sr, cr] = await Promise.all([fetch(`/api/search-integrations/blogger/settings?_t=${Date.now()}`, { cache: "no-store" }), fetch(`/api/search-integrations/blogger?_t=${Date.now()}`, { cache: "no-store" })]); const data = cr.ok ? await cr.json() : { connected: false }; setSettings(sr.ok ? await sr.json() : { configured: false }); setConnection(data); setSelected(data.blogId || ""); } catch { setSettings({ configured: false }); setConnection({ connected: false }); } }
  useEffect(() => { load(); }, []);
  async function saveSettings() { if (!clientId.trim() || !clientSecret.trim()) { setMessage("Debes ingresar el Client ID y el Client Secret."); return; } setSaving(true); setMessage(""); try { const r = await fetch("/api/search-integrations/blogger/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clientId, clientSecret }) }); const data = await r.json(); setMessage(r.ok ? "Credenciales de Blogger guardadas." : data.error || "No se pudieron guardar las credenciales."); if (r.ok) { setEditing(false); setClientSecret(""); await load(); } } finally { setSaving(false); } }
  async function selectBlog() { setSaving(true); setMessage(""); try { const r = await fetch("/api/search-integrations/blogger", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ blogId: selected }) }); const data = await r.json(); setMessage(r.ok ? `Blog seleccionado: ${data.blogName}.` : data.error || "No se pudo seleccionar el blog."); if (r.ok) await load(); } finally { setSaving(false); } }
  async function disconnect() { if (!confirm("¿Deseas desconectar Blogger?")) return; setSaving(true); try { await fetch("/api/search-integrations/blogger", { method: "DELETE" }); setMessage("Blogger desconectado."); await load(); } finally { setSaving(false); } }
  const configured = settings?.configured ?? false;
  return <section style={sectionStyle}><h2 style={{ ...h2Style, margin: 0 }}>Blogger API</h2><p className="lead-copy" style={{ fontSize: 13, margin: "4px 0 0" }}>Publica artículos en el blog de Blogger que autorice cada usuario.</p>{settings?.isAdmin && <div style={{ borderTop: "1px solid #e5e5ea", marginTop: 14, paddingTop: 14 }}><strong style={{ color: "#1d1d1f", fontSize: 13 }}>Credenciales globales de la App</strong><p className="lead-copy" style={{ fontSize: 12, margin: "2px 0 0" }}>Client ID y Client Secret de Google Cloud OAuth.</p>{!editing ? <div style={{ marginTop: 10 }}>{configured && <p className="muted" style={{ fontSize: 12 }}>Client ID: {settings.clientId}</p>}<button onClick={() => { setEditing(true); setClientId(settings.rawClientId || ""); }} className="secondary" style={secondaryButtonStyle}>{configured ? "Editar credenciales" : "Configurar credenciales"}</button></div> : <div style={{ display: "grid", gap: 10, marginTop: 12 }}><label style={{ color: "#1d1d1f", fontSize: 12 }}>Client ID<input value={clientId} onChange={(e) => setClientId(e.target.value)} style={inputStyle} /></label><label style={{ color: "#1d1d1f", fontSize: 12 }}>Client Secret<input type="password" value={clientSecret} onChange={(e) => setClientSecret(e.target.value)} style={inputStyle} /></label><div style={{ display: "flex", gap: 8 }}><button onClick={saveSettings} disabled={saving} style={disabledStyle({ ...secondaryButtonStyle, background: "#1d1d1f", color: "#fff", border: "none" }, saving)}>Guardar credenciales</button><button onClick={() => setEditing(false)} className="secondary" style={secondaryButtonStyle}>Cancelar</button></div></div>}</div>}{!allowed ? <p className="muted">No tienes permiso para publicar en Blogger.</p> : !connection ? <p className="muted">Cargando...</p> : !configured ? <p className="notice">El administrador debe configurar primero las credenciales de Blogger.</p> : connection.connected ? <><p style={{ fontSize: 13 }}>Conectado: <strong>{connection.blogName || connection.blogId}</strong>{connection.isExpired ? " (autorización expirada)" : ""}</p>{(connection.blogs?.length || 0) > 1 && <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><select value={selected} onChange={(e) => setSelected(e.target.value)}>{connection.blogs?.map((blog) => <option key={blog.id} value={blog.id}>{blog.name}</option>)}</select><button className="secondary" style={secondaryButtonStyle} disabled={saving || !selected} onClick={selectBlog}>Guardar blog</button></div>}<button className="secondary" style={secondaryButtonStyle} disabled={saving} onClick={disconnect}>Desconectar Blogger</button></> : <a className="button" href="/api/search-integrations/blogger/connect">Conectar Blogger</a>}{message && <p className="muted" style={{ fontSize: 12 }}>{message}</p>}</section>;
}
