"use client";

import { useEffect, useState } from "react";
import { disabledStyle, h2Style, inputStyle, secondaryButtonStyle, sectionStyle } from "./dashboard-ui";

export default function DevToSection({ allowed = true, isAdmin = false }: { allowed?: boolean; isAdmin?: boolean }) {
  const [connection, setConnection] = useState<{ connected: boolean; username?: string } | null>(null);
  const [apiKey, setApiKey] = useState(""); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function load() { setLoading(true); try { const r = await fetch(`/api/search-integrations/devto?_t=${Date.now()}`, { cache: "no-store" }); setConnection(r.ok ? await r.json() : { connected: false }); } catch { setConnection({ connected: false }); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function save() { if (!apiKey.trim()) { setMessage("Escribe la API key global de DEV.to."); return; } setSaving(true); setMessage(""); try { const r = await fetch("/api/search-integrations/devto", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ apiKey: apiKey.trim() }) }); const result = await r.json(); if (!r.ok) { setMessage(result.error || "No se pudo conectar DEV.to."); return; } setMessage("API key global de DEV.to guardada."); setApiKey(""); setEditing(false); await load(); } catch { setMessage("Error de conexión al guardar DEV.to."); } finally { setSaving(false); } }
  async function disconnect() { if (!confirm("¿Deseas desconectar la API key global de DEV.to?")) return; setSaving(true); try { await fetch("/api/search-integrations/devto", { method: "DELETE" }); setMessage("DEV.to desconectado."); await load(); } finally { setSaving(false); } }
  if (!allowed) return null;
  return <section style={sectionStyle}><h2 style={{ ...h2Style, margin: 0 }}>DEV.to</h2><p className="lead-copy" style={{ fontSize: 13, margin: "4px 0 0" }}>Publica una versión adaptada del artículo en Markdown con su imagen y enlace canónico.</p>{loading ? <p className="muted" style={{ fontSize: 13, marginTop: 12 }}>Cargando...</p> : <div style={{ borderTop: "1px solid #e5e5ea", marginTop: 14, paddingTop: 14 }}>{isAdmin ? (!connection?.connected || editing ? <div style={{ display: "grid", gap: 10 }}><label style={{ color: "#1d1d1f", fontSize: 12 }}>API key global de DEV.to<input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder="Pega aquí la API key de administración" style={inputStyle} /></label><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button onClick={save} disabled={saving} style={disabledStyle({ ...secondaryButtonStyle, background: "#1d1d1f", color: "#fff", border: "none" }, saving)}>{saving ? "Verificando..." : "Guardar API key global"}</button>{connection?.connected && <button onClick={() => setEditing(false)} className="secondary" style={secondaryButtonStyle}>Cancelar</button>}</div></div> : <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}><strong style={{ color: "#16803c", fontSize: 13 }}>✓ DEV.to configurado para todos los usuarios autorizados</strong><button onClick={() => setEditing(true)} className="secondary" style={secondaryButtonStyle}>Cambiar API key</button><button onClick={disconnect} disabled={saving} className="secondary" style={secondaryButtonStyle}>Desconectar</button></div>) : <p className="notice" style={{ margin: 0 }}>DEV.to está configurado por administración. Puedes publicar desde Oportunidades de Redes Sociales si tienes el permiso activado.</p>}{message && <p className="notice" style={{ margin: "12px 0 0" }}>{message}</p>}</div>}</section>;
}
