"use client";

import { useEffect, useState } from "react";
import { disabledStyle, h2Style, inputStyle, secondaryButtonStyle, sectionStyle } from "./dashboard-ui";

export default function DevToSection({ allowed = true }: { allowed?: boolean }) {
  const [connection, setConnection] = useState<{ connected: boolean; username?: string } | null>(null);
  const [apiKey, setApiKey] = useState(""); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function load() { setLoading(true); try { const r = await fetch(`/api/search-integrations/devto?_t=${Date.now()}`, { cache: "no-store" }); setConnection(r.ok ? await r.json() : { connected: false }); } catch { setConnection({ connected: false }); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const [username, setUsername] = useState("");
  async function save() { if (!apiKey.trim()) { setMessage("Escribe la API key de DEV.to."); return; } setSaving(true); setMessage(""); try { const r = await fetch("/api/search-integrations/devto", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username: username.trim(), apiKey: apiKey.trim() }) }); const result = await r.json(); if (!r.ok) { setMessage(result.error || "No se pudo conectar DEV.to."); return; } setMessage(result.username ? `DEV.to conectado como @${result.username}.` : "DEV.to conectado."); setApiKey(""); setEditing(false); await load(); } catch { setMessage("Error de conexión al guardar DEV.to."); } finally { setSaving(false); } }
  async function disconnect() { if (!confirm("¿Deseas desconectar DEV.to?")) return; setSaving(true); try { await fetch("/api/search-integrations/devto", { method: "DELETE" }); setMessage("DEV.to desconectado."); await load(); } finally { setSaving(false); } }
  if (!allowed) return null;
  return <section style={sectionStyle}><h2 style={{ ...h2Style, margin: 0 }}>DEV.to</h2><p className="lead-copy" style={{ fontSize: 13, margin: "4px 0 0" }}>Conecta la cuenta de DEV.to donde se publicarán tus artículos adaptados.</p>{loading ? <p className="muted" style={{ fontSize: 13, marginTop: 12 }}>Cargando...</p> : <div style={{ borderTop: "1px solid #e5e5ea", marginTop: 14, paddingTop: 14 }}>{!connection?.connected || editing ? <div style={{ display: "grid", gap: 10 }}><label style={{ color: "#1d1d1f", fontSize: 12 }}>Usuario de DEV.to<input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="lorena" style={inputStyle} /></label><label style={{ color: "#1d1d1f", fontSize: 12 }}>API key de DEV.to<input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder="Usa la API key, no la contraseña principal" style={inputStyle} /></label><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button onClick={save} disabled={saving} style={disabledStyle({ ...secondaryButtonStyle, background: "#1d1d1f", color: "#fff", border: "none" }, saving)}>{saving ? "Verificando..." : "Conectar DEV.to"}</button>{connection?.connected && <button onClick={() => setEditing(false)} className="secondary" style={secondaryButtonStyle}>Cancelar</button>}</div></div> : <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}><strong style={{ color: "#16803c", fontSize: 13 }}>✓ Conectado{connection.username ? ` como @${connection.username}` : ""}</strong><button onClick={() => setEditing(true)} className="secondary" style={secondaryButtonStyle}>Cambiar cuenta</button><button onClick={disconnect} disabled={saving} className="secondary" style={secondaryButtonStyle}>Desconectar</button></div>}{message && <p className="notice" style={{ margin: "12px 0 0" }}>{message}</p>}</div>}</section>;
}
