"use client";
import { useEffect, useState } from "react";
import { disabledStyle, h2Style, inputStyle, secondaryButtonStyle, sectionStyle } from "./dashboard-ui";

export default function MastodonSection({ allowed = true }: { allowed?: boolean }) {
  const [connection, setConnection] = useState<{ connected: boolean; instanceUrl?: string; username?: string; displayName?: string } | null>(null);
  const [instanceUrl, setInstanceUrl] = useState("https://mastodon.social"); const [accessToken, setAccessToken] = useState(""); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function load() { const response = await fetch(`/api/search-integrations/mastodon?_t=${Date.now()}`, { cache: "no-store" }); const next = response.ok ? await response.json() : { connected: false }; setConnection(next); if (next.instanceUrl) setInstanceUrl(next.instanceUrl); }
  useEffect(() => { load().catch(() => setConnection({ connected: false })); }, []);
  async function save() { if (!instanceUrl.trim() || !accessToken.trim()) { setMessage("Escribe la instancia y el Access Token de Mastodon."); return; } setSaving(true); setMessage(""); try { const response = await fetch("/api/search-integrations/mastodon", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ instanceUrl, accessToken }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error || "No se pudo conectar Mastodon."); return; } setMessage(`Mastodon conectado como @${result.username}.`); setAccessToken(""); setEditing(false); await load(); } catch { setMessage("Error de conexión al guardar Mastodon."); } finally { setSaving(false); } }
  async function disconnect() { if (!confirm("¿Deseas desconectar Mastodon?")) return; await fetch("/api/search-integrations/mastodon", { method: "DELETE" }); setMessage("Mastodon desconectado."); await load(); }
  if (!allowed) return null;
  return <section style={sectionStyle}><h2 style={{ ...h2Style, margin: 0 }}>Mastodon</h2><p className="lead-copy" style={{ fontSize: 13, margin: "4px 0 0" }}>Publica un texto adaptado con imagen y enlace en tu instancia.</p><div style={{ borderTop: "1px solid #e5e5ea", marginTop: 14, paddingTop: 14 }}>{!connection?.connected || editing ? <div style={{ display: "grid", gap: 10 }}><label style={{ color: "#1d1d1f", fontSize: 12 }}>URL de tu instancia<input value={instanceUrl} onChange={e => setInstanceUrl(e.target.value)} placeholder="https://mastodon.social" style={inputStyle} /></label><label style={{ color: "#1d1d1f", fontSize: 12 }}>Access Token<input type="password" value={accessToken} onChange={e => setAccessToken(e.target.value)} placeholder="Pégalo aquí" style={inputStyle} /></label><button onClick={save} disabled={saving} style={disabledStyle({ ...secondaryButtonStyle, background: "#1d1d1f", color: "#fff", border: "none" }, saving)}>{saving ? "Verificando..." : "Conectar Mastodon"}</button></div> : <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}><strong style={{ color: "#16803c", fontSize: 13 }}>✓ Conectado como @{connection.username}</strong><button onClick={() => setEditing(true)} className="secondary" style={secondaryButtonStyle}>Cambiar cuenta</button><button onClick={disconnect} disabled={saving} className="secondary" style={secondaryButtonStyle}>Desconectar</button></div>}{message && <p className="notice" style={{ margin: "12px 0 0" }}>{message}</p>}</div></section>;
}
